version: '3'
services:
  maven:
    build:
      context: .
      dockerfile: M.Dockerfile
    container_name: maven-container
    volumes:
      - shared_data:/usr/src/app/target/
  tomcat:
    build:
      image: tomcat:9.0-jre8-alpine
    container_name: tomcat-container
    volumes:
      - shared_data:/usr/src/app/target/
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - maven
volumes:
  shared_data: