version: '3'
  services:
    maven:
      build:
        context: docker/maven/
        dockerfile: M.Dockerfile
      container_name: maven-container
      restart: unless-stopped
    tomcat:
      build:
        context: docker/tomcat/
          dockerfile: T.Dockerfile
      container_name: tomcat-container
      restart: unless-stopped
      ports: 8080:8080
      depends_on: maven