version: '3'
services:
  maven:
    build:
      context: .
      dockerfile: M.Dockerfile
    container_name: maven-container
    restart: unless-stopped
  tomcat:
    build:
      context: .
      dockerfile: T.Dockerfile
    container_name: tomcat-container
    restart: unless-stopped
    ports:
      - 8080:8080
    depends_on:
      - maven
